FROM mcr.microsoft.com/dotnet/sdk:6.0 AS development

WORKDIR /usr/src/dev_trybe-hotel

EXPOSE 5057

COPY . ./

COPY . ./.entity-framework

RUN dotnet restore

RUN dotnet restore ./.entity-framework

ENTRYPOINT dotnet tool restore \
&& dotnet watch run --project ./TrybeHotel.csproj